research-visualizer-title = Research Visualizer
research-visualizer-points = Points: { $points }
research-visualizer-mode = Mode: { $mode }
research-visualizer-disk = Disk: { $name }
research-visualizer-no-disk = No disk inserted
research-collected-technologies = Collected Technologies
research-no-technologies = No technologies collected
research-technology-tooltip = Technology: { $tech }
research-tooltip-eject-disk = Eject Disk
research-error-too-far = You are too far away
research-error-no-visualizer = Visualizer not found
research-disk-invalid = Invalid disk
research-disk-already-used = Disk already used
research-points-max-reached = Maximum points reached
research-disk-inserted = Disk inserted! Gained { $points } points
research-disk-ejected = Disk ejected